Progress page
MartinezNicanor/IT1E-period-4 pull request #52
Opened 2023-06-19 12:04 UTC by MichIoan

2023-06-21 12:19 UTC, izabelarybinska requested changes
make the headings (php, java, html/css) bigger (about 1.5vw) or change it to h3 instead of h4. Make the height of the progress bar a little bigger (35px), other than that its good

2023-06-23 09:38 UTC, MartinezNicanor approved these changes
LGTM!

2023-06-23 09:45 UTC, MartinezNicanor approved these changes
LGTM!

2023-06-23 09:47 UTC, izabelarybinska approved these changes

2023-06-23 09:47 UTC, merged